#!/bin/bash

set -e

if [ -f /gopath/src/app/.godir  ]; then
    GODIR=$(cat /gopath/src/app/.godir)
    mkdir -p /gopath/src/$(dirname ${GODIR})
    ls -ld /gopath/src/${GODIR} &>/dev/null || ln -s /gopath/src/app /gopath/src/${GODIR}
    go get ${GODIR}
else
    go get app
fi
